export const CategoryList = [
  "Hemşire",
  "Diyetisyen",
  "KİŞİSEL GELİŞİM / KOÇLUK",
  "TÜM ÖZEL DERS",
  "Psikolog",
  "Masaj",
  "Evden Eve Nakliye",
  "Şehir İçi Nakliye",
  "Şehirlerarası Nakliye",
  "ORGANİZASYON",
  "TEMİZLİK",
  "BİNA DIŞ CEPHE",
  "Boya Badana",
  "CAM BALKON",
  "Camcı",
  "ÇATI TAMİRİ",
  "PARKE DÖŞEME",
  "DOĞRAMA",
  "DUŞAKABİN",
  "Duvar Kağıdı Ustası",
  "ELEKTRİKÇİ",
  "Fayans Seramik Ustası",
  "HALI KOLTUK YIKAMA",
  "Havuz Bakımı",
  "Havuz Yapımı",
  "İÇ DEKORASYON",
  "KALÖRİFER TAMİR BAKIM",
  "KLİMA MONTAJ / TAMİR",
  "KOMBİ MONTAJ / TAMİR",
  "Mermer ve Granit Ustası",
  "Mobilya Boya Cila",
  "Mobilya Döşeme",
  "Mobilya Montajı",
  "Mobilya Tamir Bakım",
  "Panjur",
  "Parke Sistre Cilalama",
  "PVC Yer Kaplaması Ustası",
  "SU TESİSATÇISI",
  "TADİLAT",
  "TENTE BRANDA TERAS KAPAMA",
];
